#!/usr/bin/env bash
# Pure helpers over docker/allowed-domains.txt.
#
# Sourced by init-firewall.sh (as root at container start) and by
# scripts/tests/test-sandbox-allowlist.sh (no root, no network, no docker) —
# keep everything in here side-effect free so the logic stays unit-testable.

# allowlist_domains FILE
# Prints one validated, lowercased domain per line. Blank lines and `#` comments
# (whole-line or trailing) are dropped; surrounding whitespace is ignored.
# Exits 1 naming the first invalid line, printing nothing further.
allowlist_domains() {
  local file="$1" raw line n=0
  while IFS= read -r raw || [ -n "$raw" ]; do
    n=$((n + 1))
    line="${raw%%#*}"             # strip a trailing comment
    line="${line//[[:space:]]/}"  # strip all whitespace
    [ -z "$line" ] && continue
    line="${line,,}"
    if [[ "$line" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$ ]]; then
      printf '%s\n' "$line"
    else
      echo "allowed-domains: invalid entry at $file:$n: '$raw'" >&2
      return 1
    fi
  done <"$file"
}

# dnsmasq_conf FILE UPSTREAM...
# Prints a dnsmasq configuration that forwards ONLY the allowlisted domains (and
# their subdomains) to the given upstream resolvers and adds every IPv4 they
# resolve to into the `allowed-domains` ipset at resolution time.
#
# There is deliberately no bare `server=` line: a name that is not allowlisted is
# refused locally, so it never reaches the upstream resolver (no DNS tunnelling)
# and never obtains an IP that iptables could be asked about.
dnsmasq_conf() {
  local file="$1"; shift
  local upstreams=("$@") domains d up
  if [ "${#upstreams[@]}" -eq 0 ]; then
    echo "dnsmasq_conf: at least one upstream resolver is required" >&2
    return 1
  fi
  domains="$(allowlist_domains "$file")" || return 1

  printf '%s\n' \
    '# generated by init-firewall.sh from docker/allowed-domains.txt' \
    'no-resolv' \
    'no-poll' \
    'listen-address=127.0.0.1' \
    'bind-interfaces' \
    'filter-AAAA'
  while IFS= read -r d; do
    [ -n "$d" ] || continue
    for up in "${upstreams[@]}"; do
      printf 'server=/%s/%s\n' "$d" "$up"
    done
    printf 'ipset=/%s/allowed-domains\n' "$d"
  done <<<"$domains"
}
